### ISSUE TITLE
Use Jemoji Configuration in plugins array

### ISSUE THREAD

**Issue by cinhtau** [jekyll/jemoji#85]
Hi,

Using the latest Jekyll version 3.8.3. Instead of plugins we still have the `gems` array in the `_config.yml` for Jemoji only. This warning is issued.

`Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.`

Are there any plans to make it work with the `plugins` array? Currently, I use both.

An example

```yaml
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-email-protect
  - jekyll-gist  

gems:
  - jemoji
```
