### ISSUE TITLE
Emojis are not rendered inline

### ISSUE THREAD

**Issue by mu88** [jekyll/jemoji#92]
I'm wondering why the emojis within my [blog post](https://mu88.github.io//2019/05/25/Qooxdoo-VS-Code.html) are not rendered inline, but instead are placed on a separate line.

**Comment by ashmaroli** [comment]
This plugin just replaces `:smiley:` with the markup to render :smiley:
The issue you're facing is because of faulty CSS:
```css
img {
  display: block;
  max-width: 100%;
  margin: 0 0 1rem;
  border-radius: 5px;
}
```
