### ISSUE TITLE
emoji's are stretched

### ISSUE THREAD

**Issue by SimonEnsemble** [jekyll/jemoji#93]
hi. my jekyll website on both gihub pages and locally displays emojis as stretched. see [here](https://simonensemble.github.io/emoji/). Do you have any idea what could be going on? Thanks.

**Comment by ashmaroli** [comment]
Its because of the following CSS declaration:
```css
.content img {
  text-align: center;
  width: 100%;
}
```
